### ISSUE TITLE
Where to init this Package?

### ISSUE THREAD

**Issue by JeromeK13** [manelclos/django-oracle-backend#1]
Hey i would have a question.

We would like to use this package so my questions:

Where do i init this classes or is there an "new" option to achive this?

**Comment by manelclos** [comment]
Hi @JeromeK13,

You will add it to your `DATABASES` configuration, Django will init the classes, see how to use it in the Django documentation: https://docs.djangoproject.com/en/3.1/ref/databases/#subclassing-the-built-in-database-backends

**Comment by JeromeK13** [comment]
Thanks for the quick response, it worked 👍 
Jérôme

**Comment by manelclos** [comment]
@JeromeK13 can you send a full `DATABASES` example to add to the README.md? just in case this is useful for someone else.

**Comment by JeromeK13** [comment]
Sure in the meanwhile i found a even simpler way. I will create a PR for the README

**Comment by JeromeK13** [comment]
#2 PR is Open
